### ISSUE TITLE
List 擴展讀取錯誤

### ISSUE THREAD

**Issue by Skyhigh173** [NanHaiJuRuo/clipcc-extension-nhjrToolBox#5]
![E6883F11-3FCA-4269-803A-C4388745D77D](https://user-images.githubusercontent.com/100467674/198498592-d9d8f648-e3b1-4d03-8a07-c718898300aa.jpeg)

出現錯誤

## 預期結果

從 `[["\"9\"",0,3]]` 的第（0）項獲取值 ： "9" (scr默認) 或 `"\"9\""` （擴展自帶`""`）
從 `[["\"9\"",0,3]]` 的第（1）項獲取值 ： 0
從 `[["\"9\"",0,3]]` 的第（2）項獲取值 ： 3

**Comment by Skyhigh173** [comment]
草，弄錯了（（

**Comment by NanHaiJuRuo** [comment]
已从邮件看到内容。图中指的是clipcc自带的JSON扩展。
